# Generated by Django 2.1.3 on 2018-12-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=100)),
                ('duration', models.FloatField(max_length=5)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m3u8.App')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m3u8.Stream')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
